// <auto-generated />
using EfCoreNotNullNestedOwned;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EfCoreNotNullNestedOwned.Migrations
{
    [DbContext(typeof(ExampleContext))]
    [Migration("20221031000845_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.17");

            modelBuilder.Entity("EfCoreNotNullNestedOwned.RootEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("RootEntities");
                });

            modelBuilder.Entity("EfCoreNotNullNestedOwned.RootEntity", b =>
                {
                    b.OwnsOne("EfCoreNotNullNestedOwned.NestedOwnedEntity", "NestedOwned", b1 =>
                        {
                            b1.Property<int>("RootEntityId")
                                .HasColumnType("INTEGER");

                            b1.HasKey("RootEntityId");

                            b1.ToTable("RootEntities");

                            b1.WithOwner()
                                .HasForeignKey("RootEntityId");

                            b1.OwnsOne("EfCoreNotNullNestedOwned.SomeOwnedEntity", "SomeOwned", b2 =>
                                {
                                    b2.Property<int>("NestedOwnedEntityRootEntityId")
                                        .HasColumnType("INTEGER");

                                    b2.Property<string>("BProperty")
                                        .HasColumnType("TEXT");

                                    b2.HasKey("NestedOwnedEntityRootEntityId");

                                    b2.ToTable("RootEntities");

                                    b2.WithOwner()
                                        .HasForeignKey("NestedOwnedEntityRootEntityId");
                                });

                            b1.Navigation("SomeOwned");
                        });

                    b.OwnsOne("EfCoreNotNullNestedOwned.SimpleOwnedEntity", "SimpleOwned", b1 =>
                        {
                            b1.Property<int>("RootEntityId")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("AProperty")
                                .HasColumnType("TEXT");

                            b1.HasKey("RootEntityId");

                            b1.ToTable("RootEntities");

                            b1.WithOwner()
                                .HasForeignKey("RootEntityId");
                        });

                    b.Navigation("NestedOwned");

                    b.Navigation("SimpleOwned");
                });
#pragma warning restore 612, 618
        }
    }
}
